version: '2.1'

services:
  emailsystem-django:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DJANGO_DEBUG=True
    ports:
      - "8000:8000"
    command: ./start-dev.sh
    volumes:
      - ./:/app/
