# Generated by Django 3.0.4 on 2020-04-05 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField()),
                ('contents', models.TextField()),
                ('total', models.IntegerField(default=0)),
                ('complete', models.IntegerField(default=0)),
                ('write_date', models.DateTimeField(auto_now=True)),
                ('complete_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='emailaddress',
            name='is_use',
        ),
        migrations.AddField(
            model_name='emailaddress',
            name='is_deny',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AddressToSend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_complete', models.BooleanField(default=False)),
                ('sent_datetime', models.DateTimeField(null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_send_address', to='api.EmailAddress')),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_send_mail', to='api.EmailAddress')),
            ],
        ),
    ]
