# Generated by Django 3.0.4 on 2020-04-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200408_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='write_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
