# Generated by Django 3.0.4 on 2020-04-08 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200408_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresstosend',
            name='mail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_send_mail', to='api.Email'),
        ),
    ]
