# Generated by Django 3.0.4 on 2020-04-08 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200408_1719'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddressToSend',
            new_name='MailTask',
        ),
        migrations.AlterField(
            model_name='mailtask',
            name='mail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_send_mail', to='api.Email'),
        ),
    ]
