# Generated by Django 3.0.4 on 2020-04-08 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200408_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='state',
            field=models.IntegerField(choices=[(1, 'Not Start'), (2, 'Processing'), (3, 'Complete')], default=1),
        ),
        migrations.AlterField(
            model_name='mailtask',
            name='mail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_send_mail', to='api.Email'),
        ),
    ]
